### ISSUE TITLE
[small] Syntax Highlighting

### ISSUE THREAD

**Issue by drschatz** [drschatz/cs-128-live-web#14]
Add syntax highlighting to the markdown files like "RMEs"

**Comment by Lumi-works** [comment]
add the code syntax highlight: 
<img width="1512" alt="Screenshot 2024-08-25 at 7 19 09 AM" src="https://github.com/user-attachments/assets/f6ce6493-cafa-4409-a823-5f353152dc69">
usage: when writing code mdx file, enclose code in three backticks with the leading backticks followed by the language (eg. ```cpp)
