### ISSUE TITLE
[Medium][Important] Get a page that has Mp1 specifications from the markdown file. 

### ISSUE THREAD

**Issue by drschatz** [drschatz/cs-128-live-web#15]
No need for an MP landing page, it will just link from the schedule directly I'm thinking.

**Comment by Lumi-works** [comment]
Added the page at "https://www.cs128live.org/course-book/mps/WordGuess".

**Comment by Lumi-works** [comment]
Add the TOC for the MPs detail page, while keep the resource page only the markdown content. Resource page: https://www.cs128live.org/course-book/resource/Workspaces; MPs page: https://www.cs128live.org/course-book/mps/WordGuess 
<img width="1512" alt="Screenshot 2024-08-24 at 5 09 50 PM" src="https://github.com/user-attachments/assets/25a82d15-b16e-4956-8870-2cc9fdf6ed90">
<img width="1512" alt="Screenshot 2024-08-24 at 5 10 08 PM" src="https://github.com/user-attachments/assets/87d8a062-3bcd-4dab-a112-d40eb1f6f845">

**Comment by drschatz** [comment]
It looks great but the TOC for the MP doesn't work when I click it.

**Comment by Lumi-works** [comment]
Thanks for the reminding, just fixed.
