### ISSUE TITLE
[medium][Important] Adding lecture numbers to schedule

### ISSUE THREAD

**Issue by drschatz** [drschatz/cs-128-live-web#17]
On the schedule (front page and schedule page) I would like to add lecture numbering to match the slides and recordings. The system I've been using is week.lec_number so the first week there is 1.1, 1.2, 1.3 and next week since there is no class Monday there is just 2.1, and 2.2.

**Comment by Lumi-works** [comment]
Lecture number added (till week5 TBD)
<img width="1512" alt="Screenshot 2024-08-29 at 8 27 29 PM" src="https://github.com/user-attachments/assets/85582ecc-b923-402e-9dce-1ce20cf9dc52">
