### ISSUE TITLE
[Small][Important] Add white space at the bottom of MP spec pages

### ISSUE THREAD

**Issue by drschatz** [drschatz/cs-128-live-web#18]

**Comment by Lumi-works** [comment]
Before:
<img width="1512" alt="Screenshot 2024-08-29 at 8 30 42 PM" src="https://github.com/user-attachments/assets/8e48b447-c02a-4fc2-acf6-3727a5de6b6f">
Now:
<img width="1512" alt="Screenshot 2024-08-29 at 8 31 19 PM" src="https://github.com/user-attachments/assets/53c11c6d-9a2d-4078-a4ef-21cc6aeff7a0">
