### ISSUE TITLE
[Medium][Important] Create an MP page just like the resources page (start it with no MPs yet)

### ISSUE THREAD

**Issue by drschatz** [drschatz/cs-128-live-web#19]

**Comment by Lumi-works** [comment]
I set the MP 1 block to be displayed when its "2024-09-06 09:00:00" CST; same for mp2 and mp3 but with a fake date
`const targetDateTimeMP1 = new Date("2024-09-06T09:00:00-06:00");` 

I also set up the MPs nav link to be shown in the header when the time is after 2024-09-06 09:00:00 CST.

<img width="1512" alt="Screenshot 2024-08-29 at 8 49 48 PM" src="https://github.com/user-attachments/assets/3f31cb22-96b2-4a67-b21f-9f2135be984b">

<img width="1512" alt="Screenshot 2024-08-29 at 8 54 45 PM" src="https://github.com/user-attachments/assets/5f8e9f1b-8862-4f5c-9388-bb81ffda062e">
